# Site
name: "EconThaki"
title: "EconThaki"
description: "EconThaki por una academia diversa"
meta_description: "EconThaki por una academia diversa"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'

email: 'econ.mentoringp@gmail.com'
google_analytics: 'G-2BG8KTZQ3G'

disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  econthaki:
    name: EconThaki
    display_name: EconThaki
    email: econ.mentoringp@gmail.com
    web: https://econthaki.github.io
    twitter: https://twitter.com/EconThaki
    description: "EconThaki por una academia diversa"
  selene:
    name: Selene
    display_name: Selene
    email: scueva@povertyactionlab.org
    twitter: https://twitter.com/selenedelpi
    description: "Selene es investigadora en JPAL"
  brian:
    name: Brian
    display_name: Brian
    email: dazavbn@gmail.com
    twitter: https://twitter.com/bdazav
    description: "Brian es alumno de PhD en la Universidad de Michigan"
  paola:
    name: Paola
    display_name: Paola
    email: 
    twitter: 
    description: ""
  gabriela: 
    name: Gabriela
    display_name: Gabriela
    email: 
    twitter: 
    description: ""
  marcy: 
    name: Marcy
    display_name: Marcy
    email: 
    twitter: 
    description: ""    
  jostin:  
    name: Jostin
    display_name: Jostin
    email: 
    twitter: 
    description: ""    


# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge