# Site
name: "EconThaki"
title: "EconThaki"
description: "EconThaki por una academia diversa"
meta_description: "EconThaki por una academia diversa"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'econ.mentoringp@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: EconThaki
    display_name: EconThaki
    gravatar: 
    email: econ.mentoringp@gmail.com
    web: https://econmentoringla.github.io
    twitter: 
    description: "EconThaki por una academia diversa"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge